from tabulate import tabulate
from Property import Property
from CommercialProperty import CommercialProperty
from PropertyAgent import PropertyAgent
from PropertyAgencyDirector import PropertyAgencyDirector
from CommissionSlip import CommissionSlip

# Example Usage
def main():
    # Create an agency
    agency = CommissionSlip()
    
    # Create a director
    director = PropertyAgencyDirector(company="Propnex", agent_registration_number="D123", start_year=2000, commission_sharing_rate=75, overriding_rate=5, director_name="Titus Ong")
    director2 = PropertyAgencyDirector(company="ERA", agent_registration_number="D456", start_year=2004, commission_sharing_rate=80, overriding_rate=10, director_name="Ben Foo")

    # Create a property agent and assign the director
    agent1 = PropertyAgent(company= "Propnex", agent_registration_number ="A123", start_year = 2012, commission_sharing_rate=70, agent_name="Lim Wei")
    agent2 = PropertyAgent(company= "Propnex", agent_registration_number ="A345", start_year = 2011, commission_sharing_rate=70, agent_name="Tan Mei")
    agent3 = PropertyAgent(company= "Propnex", agent_registration_number ="A678", start_year = 2015, commission_sharing_rate=70, agent_name="Ong Jun")
    agent4 = PropertyAgent(company= "Propnex", agent_registration_number ="A987", start_year = 2018, commission_sharing_rate=70, agent_name="Lee Min")
    agent5 = PropertyAgent(company= "ERA", agent_registration_number ="A426", start_year = 2010, commission_sharing_rate=70, agent_name="Chua Yan")
    agent6 = PropertyAgent(company= "ERA", agent_registration_number ="A837", start_year = 2013, commission_sharing_rate=70, agent_name="Goh Kai")
    agent7 = PropertyAgent(company= "ERA", agent_registration_number ="A934", start_year = 2019, commission_sharing_rate=70, agent_name="Teo Ling")
    director.add_agent(agent1)
    director.add_agent(agent2)
    director.add_agent(agent3)
    director.add_agent(agent4)
    director2.add_agent(agent5)
    director2.add_agent(agent6)
    director2.add_agent(agent7)

    # Add agent and director to agency
    agency.add_agent(agent1)
    agency.add_agent(agent2)
    agency.add_agent(agent3)
    agency.add_agent(agent4)
    agency.add_agent(agent5)
    agency.add_agent(agent6)
    agency.add_agent(agent7)
    agency.add_director(director)
    agency.add_director(director2)
    
    # Add unsold properties that managed by director and sold
    drp1 = Property(address="789 Pine St", postal_code=789012, tenure="Freehold", completion_year=2021, property_type="Residential", area=1300, valuation=450000, commission_rate=0.01)
    drp2 = Property(address="1 Lorng 5 Toa Payoh", postal_code=349582, tenure="Leasehold", completion_year=2021, property_type="Residential", area=1500, valuation=500000, commission_rate=0.01)
    drp3 = CommercialProperty(address="4 Lorng 5 Toa Payoh", postal_code=165484, tenure="Freehold", completion_year=2005, property_type="Commercial", area=1000, valuation=800000, commercial_type="Office",commission_rate=0.01)
    # Changed to director selling the property
    director.add_property_sold(drp1)
    director.add_property_sold(drp3)    
    director2.add_property_sold(drp2)

    # Add sold properties by director to agency
    agency.add_property(drp1)
    agency.add_property(drp2)
    agency.add_property(drp3)

    # Create properties  
    # Creat sold residential properties = Agent 1
    rp1 = Property(address="17 Nassim Road", postal_code=258390, tenure="Freehold", completion_year=1971, property_type="Residential", area=782, valuation=1096187, commission_rate=0.01)
    rp2 = Property(address="5 Caldecott Close", postal_code=299855, tenure="Commonhold", completion_year=1984, property_type="Residential", area=1163, valuation=1821789, commission_rate=0.01)
    # Creat sold residential properties = Agent 2   
    rp3 = Property(address="467 Ang Mo Kio Avenue 10", postal_code=560467, tenure="Leasehold", completion_year=2001, property_type="Residential", area=1289, valuation=2025432, commission_rate=0.01)
    rp4 = Property(address="581A Sembawang Place", postal_code=751581, tenure="Freehold", completion_year=1978, property_type="Residential", area=1345, valuation=2108109, commission_rate=0.01)
    # Creat sold residential properties = Agent 3
    rp5 = Property(address="7 Raffles Boulevard", postal_code=395956, tenure="Freehold", completion_year=1969, property_type="Residential", area=1245, valuation=1798765, commission_rate=0.01)
    rp6 = Property(address="22 Upper East Coast Road", postal_code=455283, tenure="Freehold", completion_year=2015, property_type="Residential", area=612, valuation=1049999, commission_rate=0.01)
    rp7 = Property(address="3 Sentosa Gateway", postal_code=985449, tenure="Leasehold", completion_year=2020, property_type="Residential", area=1478, valuation=2309876, commission_rate=0.01)
    # Creat sold residential properties = Agent 4
    rp8 = Property(address="15 Jalan Kukoh", postal_code=161015, tenure="Commonhold", completion_year=1973, property_type="Residential", area=1076, valuation=1709876, commission_rate=0.01)
    rp9 = Property(address="10 Tanjong Katong Road", postal_code=437028, tenure="Freehold", completion_year=1985, property_type="Residential", area=790, valuation=1096210, commission_rate=0.01)
    rp10 = Property(address="9 Joo Chiat Place", postal_code=427942, tenure="Freehold", completion_year=2005, property_type="Residential", area=675, valuation=1051987, commission_rate=0.01)
    rp11 = Property(address="32 New Upper Changi Road", postal_code=461032, tenure="Leasehold", completion_year=1967, property_type="Residential", area=502, valuation=1014999, commission_rate=0.01)    
    # Creat sold residential properties = Agent 5
    rp12 = Property(address="7 Lorong 6 Toa Payoh", postal_code=310007, tenure="Freehold", completion_year=2024, property_type="Residential", area=1423, valuation=2196543, commission_rate=0.01)
    rp13 = Property(address="33 Bukit Batok Street 52", postal_code=650033, tenure="Commonhold", completion_year=1982, property_type="Residential", area=1376, valuation=2143210, commission_rate=0.01)
    rp14 = Property(address="12 Tiong Bahru Road", postal_code=168732, tenure="Freehold", completion_year=1991, property_type="Residential", area=620, valuation=1014999, commission_rate=0.01)    
    # Creat sold residential properties = Agent 6
    rp15 = Property(address="18 Dover Crescent", postal_code=130018, tenure="Leasehold", completion_year=2007, property_type="Residential", area=1489, valuation=2332345, commission_rate=0.01)
    rp16 = Property(address="26 Marine Parade Road", postal_code=449306, tenure="Freehold", completion_year=2019, property_type="Residential", area=1156, valuation=1728910, commission_rate=0.01)
    rp17 = Property(address="9 Jurong East Street 21", postal_code=600009, tenure="Commonhold", completion_year=1966, property_type="Residential", area=876, valuation=1598765, commission_rate=0.01)    
    rp18 = Property(address="16 Choa Chu Kang Avenue 4", postal_code=689832, tenure="Freehold", completion_year=1989, property_type="Residential", area=695, valuation=1053210, commission_rate=0.01)
    rp19 = Property(address="27 Woodlands Avenue", postal_code=339411, tenure="Freehold", completion_year=2014, property_type="Residential", area=542, valuation=1014999, commission_rate=0.01) 
    # Creat sold residential properties = Agent 7 
    rp20 = Property(address="30 Bishan Street 13", postal_code=579792, tenure="Commonhold", completion_year=2004, property_type="Residential", area=753, valuation=1096210, commission_rate=0.01)
    rp21 = Property(address="17 Bukit Timah Road", postal_code=267787, tenure="Leasehold", completion_year=2016, property_type="Residential", area=1312, valuation=1809876, commission_rate=0.01)
    rp22 = Property(address="20 Buona Vista Drive", postal_code=138649, tenure="Leasehold", completion_year=1983, property_type="Residential", area=1500, valuation=2500000, commission_rate=0.01)    
    rp23 = Property(address="35 Pasir Panjang Road", postal_code=118494, tenure="Freehold", completion_year=2006, property_type="Residential", area=830, valuation=1576543, commission_rate=0.01)  

    # Creat sold commercial properties = Agent 1 
    cp1 = CommercialProperty(address="49 Lim Liak Street", postal_code=161049, tenure="Freehold", completion_year=1995, property_type="Commercial", area=905, valuation=1412345, commercial_type="Flatted factory", commission_rate=0.01)
    # Creat sold commercial properties = Agent 2 
    cp2 = CommercialProperty(address="1 Cleantech Loop", postal_code=637141, tenure="Commonhold", completion_year=2010, property_type="Commercial", area=1289, valuation=2025432, commercial_type="Office", commission_rate=0.01)
    cp3 = CommercialProperty(address="13 Boat Quay Conservation Area", postal_code=498425, tenure="Leasehold", completion_year=1987, property_type="Commercial", area=587, valuation=1014999, commercial_type="Factory", commission_rate=0.01)
    # Creat sold commercial properties = Agent 3
    cp4 = CommercialProperty(address="9 Tampines Central 1", postal_code=529536, tenure="Leasehold", completion_year=1981, property_type="Commercial", area=1245, valuation=1187654, commercial_type="Factory", commission_rate=0.01)
    cp5 = CommercialProperty(address="2 Orchard Turn", postal_code=238801, tenure="Commonhold", completion_year=1996, property_type="Commercial", area=1398, valuation=2154321, commercial_type="Office", commission_rate=0.01)
    # Creat sold commercial properties = Agent 4
    cp6 = CommercialProperty(address="21 Changi Business Part Central 1", postal_code=486070, tenure="Leasehold", completion_year=1993, property_type="Commercial", area=1298, valuation=1819876, commercial_type="Flatted factory", commission_rate=0.01)
    cp7 = CommercialProperty(address="25 Telok Blangah Crescent", postal_code=900250, tenure="Commonhold", completion_year=2018, property_type="Commercial", area=1349, valuation=2132109, commercial_type="Factory", commission_rate=0.01)
    # Creat sold commercial properties = Agent 5
    cp8 = CommercialProperty(address="45 Hillview Avenue", postal_code=669813, tenure="Freehold", completion_year=1979, property_type="Commercial", area=1200, valuation=1765432, commercial_type="Office", commission_rate=0.01)
    cp9 = CommercialProperty(address="28 Farrer Road", postal_code=268828, tenure="Leasehold", completion_year=1988, property_type="Commercial", area=938, valuation=1632109, commercial_type="Factory", commission_rate=0.01)
    cp10 = CommercialProperty(address="19 Rochor Road", postal_code=188436, tenure="Commonhold", completion_year=2003, property_type="Commercial", area=567, valuation=1014999, commercial_type="Flatted factory", commission_rate=0.01)
    cp11 = CommercialProperty(address="11 Clementi Avenue 3", postal_code=129907, tenure="Leasehold", completion_year=1976, property_type="Commercial", area=802, valuation=1565432, commercial_type="Factory", commission_rate=0.01)
    # Creat sold commercial properties = Agent 6
    cp12 = CommercialProperty(address="14 Ang Mo Kio Avenue 4", postal_code=560014, tenure="Leasehold", completion_year=1974, property_type="Commercial", area=1410, valuation=2265432, commercial_type="Factory", commission_rate=0.01)
    cp13 = CommercialProperty(address="24 Serangoon North Avenue 1", postal_code=555854, tenure="Leasehold", completion_year=2002, property_type="Commercial", area=1365, valuation=2120987, commercial_type="Office", commission_rate=0.01)
    cp14 = CommercialProperty(address="5 Kallang Avenue", postal_code=339411, tenure="Freehold", completion_year=1968, property_type="Commercial", area=1221, valuation=1786543, commercial_type="Factory", commission_rate=0.01)
    # Creat sold commercial properties = Agent 7
    cp15 = CommercialProperty(address="8 Punggol Drive", postal_code=828805, tenure="Leasehold", completion_year=1980, property_type="Commercial", area=981, valuation=1678910, commercial_type="Flatted factory", commission_rate=0.01)
    cp16 = CommercialProperty(address="13 Pasir Ris Drive 6", postal_code=510013, tenure="Freehold", completion_year=1990, property_type="Commercial", area=1445, valuation=1887654, commercial_type="Office", commission_rate=0.01)
    cp17 = CommercialProperty(address="6 Toh TUck Road", postal_code=596680, tenure="Freehold", completion_year=1972, property_type="Commercial", area=644, valuation=1014999, commercial_type="Factory", commission_rate=0.01)
    cp18 = CommercialProperty(address="22 Geyland East Avenue 1", postal_code=389771, tenure="Commonhold", completion_year=1994, property_type="Commercial", area=1123, valuation=1821987, commercial_type="Flatted factory", commission_rate=0.01)
    cp19 = CommercialProperty(address="19 Mountbatten Road", postal_code=398007, tenure="Leasehold", completion_year=2021, property_type="Commercial", area=1278, valuation=1819876, commercial_type="Office", commission_rate=0.01)

    # Add residencial properties to agency
    agency.add_property(rp1)
    agency.add_property(rp2)
    agency.add_property(rp3)
    agency.add_property(rp4)
    agency.add_property(rp5)
    agency.add_property(rp6)
    agency.add_property(rp7)
    agency.add_property(rp8)
    agency.add_property(rp9)
    agency.add_property(rp10)
    agency.add_property(rp11)
    agency.add_property(rp12)
    agency.add_property(rp13)
    agency.add_property(rp14)
    agency.add_property(rp15)
    agency.add_property(rp16)
    agency.add_property(rp17)
    agency.add_property(rp18)
    agency.add_property(rp19)
    agency.add_property(rp20)
    agency.add_property(rp21)
    agency.add_property(rp22)
    agency.add_property(rp23)
    # Add commercial properties to agency
    agency.add_property(cp1)
    agency.add_property(cp2)
    agency.add_property(cp3)
    agency.add_property(cp4)
    agency.add_property(cp5)
    agency.add_property(cp6)
    agency.add_property(cp7)
    agency.add_property(cp8)
    agency.add_property(cp9)
    agency.add_property(cp10)
    agency.add_property(cp11)
    agency.add_property(cp12)
    agency.add_property(cp13)
    agency.add_property(cp14)
    agency.add_property(cp15)
    agency.add_property(cp16)
    agency.add_property(cp17)
    agency.add_property(cp18)
    agency.add_property(cp19)
    # Add sold residential properties to agents
    agent1.add_property_sold(rp1)
    agent1.add_property_sold(rp2)
    agent2.add_property_sold(rp3)
    agent2.add_property_sold(rp4)
    agent3.add_property_sold(rp5)
    agent3.add_property_sold(rp6)
    agent3.add_property_sold(rp7)
    agent4.add_property_sold(rp8)
    agent4.add_property_sold(rp9)
    agent4.add_property_sold(rp10)
    agent4.add_property_sold(rp11)
    agent5.add_property_sold(rp12)
    agent5.add_property_sold(rp13)
    agent5.add_property_sold(rp14)
    agent6.add_property_sold(rp15)
    agent6.add_property_sold(rp16)
    agent6.add_property_sold(rp17)
    agent6.add_property_sold(rp18)
    agent6.add_property_sold(rp19)
    agent7.add_property_sold(rp20)
    agent7.add_property_sold(rp21)
    agent7.add_property_sold(rp22)
    agent7.add_property_sold(rp23)
    # Add sold commercial properties to agents
    agent1.add_property_sold(cp1)
    agent2.add_property_sold(cp2)
    agent2.add_property_sold(cp3)
    agent3.add_property_sold(cp4)
    agent3.add_property_sold(cp5)
    agent4.add_property_sold(cp6)
    agent4.add_property_sold(cp7)
    agent5.add_property_sold(cp8)
    agent5.add_property_sold(cp9)
    agent5.add_property_sold(cp10)
    agent5.add_property_sold(cp11)
    agent6.add_property_sold(cp12)
    agent6.add_property_sold(cp13)
    agent6.add_property_sold(cp14)
    agent7.add_property_sold(cp15)
    agent7.add_property_sold(cp16)
    agent7.add_property_sold(cp17)
    agent7.add_property_sold(cp18)
    agent7.add_property_sold(cp19)
    # Add unsold properties = Agent 1
    unsold_property = Property(address="10 Queenstown Road", postal_code=149052, tenure="Commonhold", completion_year=1977, property_type="Residential", area=706, valuation=1058910, commission_rate=0.01)
    unsold_property2 = CommercialProperty(address="28 Bedok North street 3", postal_code=460028, tenure="Freehold", completion_year=1986, property_type="Commercial", area=1379, valuation=2166543, commission_rate=0.01, commercial_type="Flatted factory")
    unsold_property3= Property(address="15 Lorong 1 Toa Payoh", postal_code=310015, tenure="Leasehold", completion_year=1997, property_type="Residential", area=590, valuation=1014999, commission_rate=0.01)
    unsold_property4 = Property(address="23 Pioneer Road North", postal_code=628468, tenure="Freehold", completion_year=2009, property_type="Residential", area=1210, valuation=1776543, commission_rate=0.01)
    unsold_property5 = CommercialProperty(address="7 Jalan Bukit Merah", postal_code=150007, tenure="Commomhold", completion_year=2022, property_type="commercial", area=895, valuation=1609876, commission_rate=0.01, commercial_type="Factory")
    agent1.add_property_unsold(unsold_property)
    agent1.add_property_unsold(unsold_property2)
    agent1.add_property_unsold(unsold_property3)
    agent1.add_property_unsold(unsold_property4)
    agent1.add_property_unsold(unsold_property5)
    agency.add_property(unsold_property)
    agency.add_property(unsold_property2)
    agency.add_property(unsold_property3)
    agency.add_property(unsold_property4)
    agency.add_property(unsold_property5)

    # Add unsold properties = Agent 2
    unsold_property6 = CommercialProperty(address="12 Kembangan Road", postal_code=419113, tenure="Leasehold", completion_year=1970, property_type="Commercial", area=1333, valuation=2025432, commission_rate=0.01, commercial_type="Office")
    unsold_property7 = Property(address="29 Hougang Avenue 7", postal_code=538801, tenure="Freehold", completion_year=1975, property_type="Residential", area=511, valuation=1014999, commission_rate=0.01)
    unsold_property8= CommercialProperty(address="9 Redhill Road", postal_code=151009, tenure="Leasehold", completion_year=1998, property_type="Commercial", area=1190, valuation=1754321, commission_rate=0.01, commercial_type="Flatted factory")
    unsold_property9 = CommercialProperty(address="31 Sengkang East Way", postal_code=544931, tenure="Freehold", completion_year=2011, property_type="Commercial", area=914, valuation=1620987, commission_rate=0.01, commercial_type="Office")
    unsold_property10 = Property(address="21 Commonwealth Avenue", postal_code=149603, tenure="Freehold", completion_year=2023, property_type="Residential", area=549, valuation=1014999, commission_rate=0.01)
    agent2.add_property_unsold(unsold_property6)
    agent2.add_property_unsold(unsold_property7)
    agent2.add_property_unsold(unsold_property8)
    agent2.add_property_unsold(unsold_property9)
    agent2.add_property_unsold(unsold_property10)
    agency.add_property(unsold_property6)
    agency.add_property(unsold_property7)
    agency.add_property(unsold_property8)
    agency.add_property(unsold_property9)
    agency.add_property(unsold_property10)

    # Add unsold properties = Agent 3
    unsold_property11 = CommercialProperty(address="16 Jalan Besar", postal_code=208791, tenure="Leasehold", completion_year=1965, property_type="Commercial", area=1432, valuation=2232109, commission_rate=0.01, commercial_type="Flatted factory")
    unsold_property12 = Property(address="34 Kim Tian Road", postal_code=169257, tenure="Commonhold", completion_year=1971, property_type="Residential", area=807, valuation=1559876, commission_rate=0.01)
    unsold_property13 = Property(address="3 Yishun Avenue 9", postal_code=768893, tenure="Freehold", completion_year=1987, property_type="Residential", area=1387, valuation=2154321, commission_rate=0.01)
    unsold_property14 = Property(address="4 Woodlands Drive 50", postal_code=730004, tenure="Leasehold", completion_year=2012, property_type="Residential", area=630, valuation=1014999, commission_rate=0.01)
    unsold_property15 = CommercialProperty(address="8 Tampines Street 11", postal_code=521008, tenure="Freehold", completion_year=2020, property_type="Commercial", area=1467, valuation=2285432, commission_rate=0.01, commercial_type="Flatted factory")
    agent3.add_property_unsold(unsold_property11)
    agent3.add_property_unsold(unsold_property12)
    agent3.add_property_unsold(unsold_property13)
    agent3.add_property_unsold(unsold_property14)
    agent3.add_property_unsold(unsold_property15)
    agency.add_property(unsold_property11)
    agency.add_property(unsold_property12)
    agency.add_property(unsold_property13)
    agency.add_property(unsold_property14)
    agency.add_property(unsold_property15)
    # Add unsold properties = Agent 4
    unsold_property16 = Property(address="11 Tampines Avenue 5", postal_code=529745, tenure="Commonhold", completion_year=1973, property_type="Residential", area=1098, valuation=1715432, commission_rate=0.01)
    unsold_property17 = Property(address="6 Simei Street 3", postal_code=529897, tenure="Leasehold", completion_year=1984, property_type="Residential", area=823, valuation=1569876, commission_rate=0.01)
    unsold_property18 = CommercialProperty(address="24 East Coast Road", postal_code=428751, tenure="Freehold", completion_year=1999, property_type="Commercial", area=1265, valuation=1798765, commission_rate=0.01, commercial_type="Office")
    unsold_property19 = CommercialProperty(address="14 Bukit Panjang Ring Road", postal_code=679940, tenure="Leasehold", completion_year=2015, property_type="Commercial", area=718, valuation=1065432, commission_rate=0.01, commercial_type="Office")
    unsold_property20 = Property(address="10 Upper Serangoon Road", postal_code=347691, tenure="Commonhold", completion_year=2024, property_type="Residential", area=1356, valuation=2186543, commission_rate=0.01)
    agent4.add_property_unsold(unsold_property16)
    agent4.add_property_unsold(unsold_property17)
    agent4.add_property_unsold(unsold_property18)
    agent4.add_property_unsold(unsold_property19)
    agent4.add_property_unsold(unsold_property20)
    agency.add_property(unsold_property16)
    agency.add_property(unsold_property17)
    agency.add_property(unsold_property18)
    agency.add_property(unsold_property19)
    agency.add_property(unsold_property20)
    # Add unsold properties = Agent 5
    unsold_property21 = CommercialProperty(address="13 Bedok South Road", postal_code=460013, tenure="Freehold", completion_year=1967, property_type="Commercial", area=556, valuation=1014999, commission_rate=0.01, commercial_type="Flatted factory")
    unsold_property22 = Property(address="18 Hougang Street 51", postal_code=538718, tenure="Leasehold", completion_year=1979, property_type="Residential", area=1234, valuation=1791234, commission_rate=0.01)
    unsold_property23 = Property(address="25 Toa Payoh Lorong 6", postal_code=310025, tenure="Commonhold", completion_year=1988, property_type="Residential", area=958, valuation=1643210, commission_rate=0.01)
    unsold_property24 = CommercialProperty(address="27 Tanglin Halt Road", postal_code=141027, tenure="Freehold", completion_year=2017, property_type="Commercial", area=1473, valuation=2278765, commission_rate=0.01, commercial_type="Factory")
    unsold_property25 = CommercialProperty(address="7 Hill Street", postal_code=179980, tenure="Leasehold", completion_year=2018, property_type="Commercial", area=726, valuation=1068910, commission_rate=0.01, commercial_type="Flatted factory")
    agent5.add_property_unsold(unsold_property21)
    agent5.add_property_unsold(unsold_property22)
    agent5.add_property_unsold(unsold_property23)
    agent5.add_property_unsold(unsold_property24)
    agent5.add_property_unsold(unsold_property25)
    agency.add_property(unsold_property21)
    agency.add_property(unsold_property22)
    agency.add_property(unsold_property23)
    agency.add_property(unsold_property24)
    agency.add_property(unsold_property25)
    # Add unsold properties = Agent 6
    unsold_property26 = Property(address="5 Harbourfront Walk", postal_code=985850, tenure="Freehold", completion_year=1969, property_type="Residential", area=1324, valuation=1812345, commission_rate=0.01)
    unsold_property27 = Property(address="1 Sentosa Island", postal_code=982690, tenure="Commonhold", completion_year=1981, property_type="Residential", area=658, valuation=1014999, commission_rate=0.01)
    unsold_property28 = CommercialProperty(address="11 Marina Boulevard", postal_code=189400, tenure="Leasehold", completion_year=1992, property_type="Commercial", area=706, valuation=1058910, commission_rate=0.01, commercial_type="Flatted factory")
    unsold_property29 = Property(address="26 Newton Road", postal_code=307957, tenure="Freehold", completion_year=2008, property_type="Residential", area=1379, valuation=2166543, commission_rate=0.01)
    unsold_property30 = CommercialProperty(address="30 River Valley Road", postal_code=179033, tenure="Leasehold", completion_year=2021, property_type="Commercial", area=590, valuation=1014999, commission_rate=0.01, commercial_type="Office")
    agent6.add_property_unsold(unsold_property26)
    agent6.add_property_unsold(unsold_property27)
    agent6.add_property_unsold(unsold_property28)
    agent6.add_property_unsold(unsold_property29)
    agent6.add_property_unsold(unsold_property30)
    agency.add_property(unsold_property26)
    agency.add_property(unsold_property27)
    agency.add_property(unsold_property28)
    agency.add_property(unsold_property29)
    agency.add_property(unsold_property30)
    # Add unsold properties = Agent 7
    unsold_property31 = CommercialProperty(address="22 Siglap Road", postal_code=455859, tenure="Commonhold", completion_year=1976, property_type="Commercial", area=1210, valuation=1776543, commission_rate=0.01, commercial_type="Factory")
    unsold_property32 = Property(address="12 Kallang Bahru", postal_code=339720, tenure="Freehold", completion_year=1985, property_type="Residential", area=895, valuation=1609876, commission_rate=0.01)
    unsold_property33 = CommercialProperty(address="9 Jalan Jurong Kechil", postal_code=598423, tenure="Leasehold", completion_year=1995, property_type="Commercial", area=1333, valuation=2025432, commission_rate=0.01, commercial_type="Factory")
    unsold_property34 = CommercialProperty(address="4 Upper Bukit Timah Road", postal_code=418944, tenure="Commonhold", completion_year=2010, property_type="Commercial", area=511, valuation=1014999, commission_rate=0.01, commercial_type="Office")
    unsold_property35 = Property(address="50 Marina Boulevard", postal_code=567234, tenure="Freehold", completion_year=2019, property_type="Residential", area=1190, valuation=1754321, commission_rate=0.01)
    agent7.add_property_unsold(unsold_property31)
    agent7.add_property_unsold(unsold_property32)
    agent7.add_property_unsold(unsold_property33)
    agent7.add_property_unsold(unsold_property34)
    agent7.add_property_unsold(unsold_property35)
    agency.add_property(unsold_property31)
    agency.add_property(unsold_property32)
    agency.add_property(unsold_property33)
    agency.add_property(unsold_property34)
    agency.add_property(unsold_property35)


    # Print properties and agents/directors
    agency.print_properties()
    agency.print_agents_directors()


if __name__ == "__main__":
    main()